/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.awt.Component;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import modell.Dolgozo;

/**
 *
 * @author piller.a.gabor
 */
public class GUI extends javax.swing.JFrame {
    private List<Dolgozo> dolgozok = new ArrayList<>();
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        
        fajlbeolvasas("emberek.txt");
        
        comboboxFeltoltes('L', cmbLany);
        comboboxFeltoltes('F', cmbFiu);
    }
    
    private void fajlbeolvasas(String fajlNeve) {
        Path path = Paths.get(fajlNeve);
        List<String> adatok = new ArrayList<>();
        try {
            adatok = Files.readAllLines(path);
        } catch (IOException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }

        String elsoSor = adatok.get(0);
        adatok.remove(elsoSor);

        for(String adat : adatok) {
            dolgozok.add(new Dolgozo(adat, ";"));
        }

        System.out.println(dolgozok.get(2));
    }
    
    private void osszesito(char neme) {
        lblLegidosebb.setText("Legidősebb: ");
        lblLegidosebb.setText(lblLegidosebb.getText() + legidosebbDolgozo(neme));
        
        lblOsszesKor.setText("Összes kor: ");
        lblOsszesKor.setText(lblOsszesKor.getText() + osszesDolgozoKora(neme));
        
        lblHatEveDolgozo.setText("Hat éve dolgozó: ");
        lblHatEveDolgozo.setText(lblHatEveDolgozo.getText() + hatEveDolgozo(neme));
    }
    
    private int legidosebbDolgozo(char neme) {
        int legidosebb = dolgozok.get(0).getKor();
        
        for (Dolgozo dolgozo : dolgozok) {
            if(dolgozo.getNeme() == neme && dolgozo.getKor() > legidosebb) {
                legidosebb = dolgozo.getKor();
            }
        }
        
        return legidosebb;
    }
    
    private int osszesDolgozoKora(char neme) {
        int osszesKor = 0;
        
        for(Dolgozo dolgozo : dolgozok) {
            if(dolgozo.getNeme() == neme) {
                osszesKor += dolgozo.getKor();
            }
        }
        
        return osszesKor;
    }
    
    private String hatEveDolgozo(char neme) {
        String dolgozoNeve = "nincs";
        
        for(Dolgozo dolgozo : dolgozok) {
            if(dolgozo.getNeme() == neme && dolgozo.getMunkToltEv() >= 6) {
                dolgozoNeve = dolgozo.getNev();
            }
        }
        
        return dolgozoNeve;
    }

    private void comboboxFeltoltes(char neme, JComboBox combobox) {
        combobox.addItem("");
        
        for (Dolgozo dolgozo : dolgozok) {
            if(dolgozo.getNeme() == neme) {
                combobox.addItem(dolgozo.getNev());
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblLanyok = new javax.swing.JLabel();
        lblFiuk = new javax.swing.JLabel();
        cmbLany = new javax.swing.JComboBox<>();
        cmbFiu = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        lanyRadioBTN = new javax.swing.JRadioButton();
        fiuRadioBTN = new javax.swing.JRadioButton();
        lblLegidosebb = new javax.swing.JLabel();
        lblHatEveDolgozo = new javax.swing.JLabel();
        lblOsszesKor = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblMiotaDolgozik = new javax.swing.JLabel();
        lblKor = new javax.swing.JLabel();
        cbMindkettoNem = new javax.swing.JCheckBox();
        btnMent = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblLanyok.setText("Lányok");

        lblFiuk.setText("Fiúk");

        cmbLany.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbLanyItemStateChanged(evt);
            }
        });

        cmbFiu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbFiuItemStateChanged(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Összesítő"));

        buttonGroup1.add(lanyRadioBTN);
        lanyRadioBTN.setText("lány");
        lanyRadioBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lanyRadioBTNActionPerformed(evt);
            }
        });

        buttonGroup1.add(fiuRadioBTN);
        fiuRadioBTN.setText("fiú");
        fiuRadioBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiuRadioBTNActionPerformed(evt);
            }
        });

        lblLegidosebb.setText("Legidősebb:");

        lblHatEveDolgozo.setText("6 éve dolgozó:");

        lblOsszesKor.setText("Összes kor:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lanyRadioBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fiuRadioBTN))
                    .addComponent(lblLegidosebb)
                    .addComponent(lblOsszesKor)
                    .addComponent(lblHatEveDolgozo))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lanyRadioBTN)
                    .addComponent(fiuRadioBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLegidosebb, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOsszesKor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHatEveDolgozo)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Adatok"));

        lblMiotaDolgozik.setText("Mióta dolgozik:");

        lblKor.setText("Kor:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKor)
                    .addComponent(lblMiotaDolgozik))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblKor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMiotaDolgozik)
                .addContainerGap())
        );

        cbMindkettoNem.setText("Mindkettő nem");

        btnMent.setText("Ment");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLanyok)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbLany, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblFiuk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbFiu, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbMindkettoNem)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(btnMent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLanyok)
                    .addComponent(lblFiuk)
                    .addComponent(cmbLany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbFiu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(cbMindkettoNem)
                        .addGap(18, 18, 18)
                        .addComponent(btnMent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lanyRadioBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lanyRadioBTNActionPerformed
        // TODO add your handling code here:
        osszesito('L');
    }//GEN-LAST:event_lanyRadioBTNActionPerformed

    private void fiuRadioBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiuRadioBTNActionPerformed
        // TODO add your handling code here:
        osszesito('F');
    }//GEN-LAST:event_fiuRadioBTNActionPerformed

    private void cmbLanyItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbLanyItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbLanyItemStateChanged

    private void cmbFiuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbFiuItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbFiuItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMent;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbMindkettoNem;
    private javax.swing.JComboBox<String> cmbFiu;
    private javax.swing.JComboBox<String> cmbLany;
    private javax.swing.JRadioButton fiuRadioBTN;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton lanyRadioBTN;
    private javax.swing.JLabel lblFiuk;
    private javax.swing.JLabel lblHatEveDolgozo;
    private javax.swing.JLabel lblKor;
    private javax.swing.JLabel lblLanyok;
    private javax.swing.JLabel lblLegidosebb;
    private javax.swing.JLabel lblMiotaDolgozik;
    private javax.swing.JLabel lblOsszesKor;
    // End of variables declaration//GEN-END:variables
}
